// Code generated by "stringer -type=encryptionAlg -linecomment"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[encryptionAlgInvalid-0]
	_ = x[encryptionAlgAES256_GCM-1]
}

const _encryptionAlg_name = "encryptionAlgInvalidAES-256-GCM"

var _encryptionAlg_index = [...]uint8{0, 20, 31}

func (i encryptionAlg) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_encryptionAlg_index)-1 {
		return "encryptionAlg(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _encryptionAlg_name[_encryptionAlg_index[idx]:_encryptionAlg_index[idx+1]]
}
