// Code generated by "stringer -type=pwHash -linecomment"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[pwHashInvalid-0]
	_ = x[pwHashPBKDF2_HMAC_SHA256-1]
}

const _pwHash_name = "pwHashInvalidPBKDF2-HMAC-SHA256"

var _pwHash_index = [...]uint8{0, 13, 31}

func (i pwHash) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_pwHash_index)-1 {
		return "pwHash(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _pwHash_name[_pwHash_index[idx]:_pwHash_index[idx+1]]
}
